name: $(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
variables:
  - name: pdkversion
    value: 1.14.1.0
stages:
  - stage: ci
    jobs:
      - job: windows
        dependsOn: []
        pool:
          vmImage: windows-2019
        steps:
          - checkout: self
            clean: true
            displayName: checkout
          - script: choco install pdk -y --no-progress --version $(pdkversion)
            displayName: install pdk
          - powershell: |
              Import-Module "$env:ProgramFiles\Puppet Labs\DevelopmentKit\share\PowerShell\Modules\PuppetDevelopmentKit\PuppetDevelopmentKit.psd1"
              $output = Join-Path "$(Agent.TempDirectory)" "unit.xml"
              # pdk test unit --format=junit:${output} --verbose
              pdk test unit
            errorActionPreference: stop
            failOnStderr: true
            displayName: pdk test unit
          - task: PublishTestResults@2
            inputs:
              searchFolder: $(Agent.TempDirectory)
              testResultsFormat: JUnit
              testResultsFiles: "*.xml"
            displayName: publish test results
