AllCops:
  Exclude:
    - spec/fixtures/modules/**
  DisplayCopNames: true
  DisplayStyleGuide: true

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Max: 50

Metrics/LineLength:
  Max: 130

EndOfLine:
  Enabled: false