name: 2.0$(Rev:.r)

jobs:
  - job: build
    pool:
      vmImage: vs2017-win2016
    steps:
      - checkout: self
        clean: true
      - task: UseRubyVersion@0
        inputs:
          versionSpec: '>= 2.4'
          addToPath: true
      - script: |
          gem install bundler
          bundle install
          bundle exec rake spec
        enabled: true
        failOnStderr: true